CREATE USER '${USER}'@'localhost' IDENTIFIED BY '****';
CREATE USER '${USER}'@'172.31.2.%' IDENTIFIED BY '****';

GRANT ALL PRIVILEGES ON ${DATABASE}.* TO '${USER}'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ${DATABASE}.* TO '${USER}'@'172.31.2.%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
